- package-lock.json
- package.json
- src/executeCode.ts
- src/utils/auth.ts
- src/utils/config.ts
- src/utils/editor.ts
- src/utils/file.ts
- src/utils/input.ts
* Add the ability to create a target if none are already available.
* Name log files with timestamps instead of hardcoded values.
* Add validation for inputs.
* Refactor code to better organise into utils modules.
> fix(targets): create target if none are available, change log file names

- package-lock.json
- package.json
- src/commands/format/FormatCommand.ts
- src/extension.ts
- src/lint/lint.ts
Fixes https://github.com/sasjs/vscode-extension/issues/19.
Add the ability to see issues within SAS files within the text editor and the 'Problems' view.
* Added `@sasjs/lint` dependency.
* Added listeners for changes within a document and when the current document changes.
* Lint the file each time those listeners are triggered.
* Map from SASjs `Diagnostic` objects to VS Code `Diagnostic` objects.
> feat(lint): add support for live linting of SAS code

- package-lock.json
- package.json
- src/extension.ts
- src/lint/lint.ts
Fix issue with linting not being restricted to .sas files.
* Restricted linting to .sas files.
* Added JSON schema validation for `.sasjslint` file.
* Added support for filename linting.
> feat(lint): add filename linting, only lint .sas files, add schema for .sasjslint

- package-lock.json
- package.json
- src/commands/format/FormatCommand.ts
- src/extension.ts
Fixes https://github.com/sasjs/vscode-extension/issues/41.
Add an automatic formatter for SAS files.
* Updated dependency versions.
* Implemented `FormatCommand` which registers a document editor provider and runs `formatText` on the text of the document when invoked.
> feat(format): add automatic formatting for SAS files

- .git-hooks/commit-msg
- package.json
Enable pre-commit git hook enforcing conventional commits.
1. Added `.git-hooks/commit-msg`.
2. Added `postinstall` script to `package.json`
> feat(git): enabled git hook enforcing conventional commits

- package-lock.json
- package.json
- src/commands/execute-code/ExecuteCodeCommand.ts
- src/commands/execute-code/internal/configuration.ts
- src/utils/auth.ts
- src/utils/input.ts
* add the configuration for the extension's default target
* execute code on sasjs server instance (both in server and desktop mode)
> feat: run code on sasjs server (both in desktop and server mode)

- src/commands/execute-code/internal/configuration.ts
- src/utils/input.ts
> fix: remove question related to http while adding target

- package.json
- src/commands/creating-target/createTargetCommand.ts
- src/commands/execute-code/internal/configuration.ts
- src/extension.ts
- src/utils/createTarget.ts
> feat: introduce new command "create target"

- src/commands/execute-code/internal/configuration.ts
- src/utils/createTarget.ts
- src/utils/input.ts
> fix: save password in encoded form

- package.json
Updating the project title and description
> chore: name update

- src/commands/execute-code/ExecuteCodeCommand.ts
- src/commands/select-target/selectTargetCommand.ts
- src/utils/createTarget.ts
closes #322
* Whenever there's an error in the network request, it should show the error or some information related to the error in the output console.
> fix: provide logging for network requests

- package-lock.json
- package.json
Update:
@typescript-eslint/eslint-plugin from 4.29.3 to 4.33.0
> chore(deps): bump deps

- package-lock.json
- package.json
- src/commands/execute-code/ExecuteCodeCommand.ts
- src/utils/input.ts
- src/utils/target.ts
closes #330
closes #329
* bump adapter version
* reduce log in output console
* on create/select target, make it default
> fix: on create/select target, make it default

- package.json
- src/commands/delete-target/deleteTargetCommand.ts
- src/extension.ts
- src/utils/config.ts
- src/utils/createTarget.ts
- src/utils/target.ts
> feat: add command for deleting target

- src/utils/input.ts
> fix: update validator function for target name

- .github/workflows/publish.yml
- package-lock.json
- package.json
> feat: bundle vscode extension using esbuild

- src/commands/execute-code/internal/configuration.ts
- src/utils/auth.ts
- src/utils/input.ts
> fix: clientID should default to clientID1 for serverType sasjs

- package.json
- src/commands/authenticating-target/authenticateTargetCommand.ts
- src/commands/creating-target/createTargetCommand.ts
- src/commands/delete-target/deleteTargetCommand.ts
- src/commands/execute-code/ExecuteCodeCommand.ts
- src/commands/select-target/selectTargetCommand.ts
- src/commands/show-target/showTargetCommand.ts
- src/commands/sync-directories/syncDirectoriesCommand.ts
- src/extension.ts
- src/utils/auth.ts
- src/utils/config.ts
- src/utils/createTarget.ts
- src/utils/outputChannel.ts
- src/utils/target.ts
* closes #365
* closes #366 
* closes #367 
* closes #368
* closes #369
> feat: Support root level syncDirectories

- src/utils/config.ts
> fix: reduce target boilerplate

- package-lock.json
- package.json
bumping sasjs/lint to enable the additional gremlins
> fix: bump gremlin (lint)

- package-lock.json
- package.json
Adding the following rules from SASjs Lint:
* [allowedGremlins](https://github.com/sasjs/lint#allowedgremlins)
* [maxDataLineLength](https://github.com/sasjs/lint#maxdatalinelength)
* [maxHeaderLineLength](https://github.com/sasjs/lint#maxheaderlinelength)
> feat: bumping the linter

- package-lock.json
- package.json
- src/extension.ts
- src/utils/target.ts
> fix: disable extension when no workspace is opened

- package-lock.json
- package.json
- src/commands/execute-code/ExecuteCodeCommand.ts
`@sasjs/adapter` returned incorrect `webout` type when `WEBOUT` was absent in the response payload.
Related [PR](https://github.com/sasjs/adapter/pull/809).
- Bumped `@sasjs/adapter`.
> fix(execution): bumped @sasjs/adapter

- src/commands/addRemoveComment/addRemoveComment.spec.ts
- src/commands/addRemoveComment/addRemoveComment.ts
- src/extension.ts
- Make variable names consistent.
- Updated variable names in `src/commands/addRemoveComment/addRemoveComment.spec.ts`, `src/commands/addRemoveComment/addRemoveComment.ts` and `src/extension.ts`.
> chore: renamed variables to make it consistent

- package.json
- Line commenting implemented in the extension wasn't triggered in Linux.
- Fix keybinding for Linux.
- `keybindings` section of the `package.json` has been updated.
> fix(keybinding): fixed addRemoveComment for linux

- .github/workflows/publish.yml
- Replace personal access token with github access token.
- Updated `.github/workflows/publish.yml`.
> chore(github-action): fixed Semantic Release

- .github/workflows/publish.yml
> fix: release fixes

- .github/workflows/publish.yml
> chore: release fix

- .github/workflows/publish.yml
> fix: release yaml

- package-lock.json
- package.json
closes #431 
fix vulnerabilities in npm packages
bump `axios`, `esbuild` and `semantic-release`
> fix: bumped deps to remove vulnerabilities
